# Generated by Django 6.0 on 2026-01-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_city_profile_number_profile_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='zip_code',
            new_name='cep',
        ),
    ]
